In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
path='/content/drive/MyDrive/tmdb_5000_credits.csv.zip'
credits=a=pd.read_csv(path)
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [4]:
from google.colab import drive
drive.mount('/content/drive')
path='/content/drive/MyDrive/tmdb_5000_movies.csv'
movies=pd.read_csv(path)
movies.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
data=movies.merge(credits,on='title')
data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
data['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [9]:
data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [10]:
data['release_date'] = pd.to_datetime(data['release_date'])
data['release_year'] = data['release_date'].dt.year
data=data[['genres','id','keywords','overview','release_date','release_year','revenue','title','cast','crew']]

In [11]:
data.describe()

,id,release_date,release_year,revenue
count,4809.000000,4808,4808.000000,4.809000e+03
mean,57120.571429,2002-12-23 19:30:44.925124608,2002.457363,8.227511e+07
min,5.000000,1916-09-04 00:00:00,1916.000000,0.000000e+00
25%,9012.000000,1999-07-07 06:00:00,1999.000000,0.000000e+00
50%,14624.000000,2005-10-03 00:00:00,2005.000000,1.917000e+07
75%,58595.000000,2011-02-16 00:00:00,2011.000000,9.291317e+07
max,459488.000000,2017-02-03 00:00:00,2017.000000,2.787965e+09
std,88653.369849,NaN,12.424628,1.628379e+08

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   genres        4809 non-null   object
 1   id            4809 non-null   int64
 2   keywords      4809 non-null   object
 3   overview      4806 non-null   object
 4   release_date  4808 non-null   datetime64[ns]
 5   release_year  4808 non-null   float64
 6   revenue       4809 non-null   int64
 7   title         4809 non-null   object
 8   cast          4809 non-null   object
 9   crew          4809 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 375.8+ KB

In [13]:
data.isnull().sum()

genres          0
id              0
keywords        0
overview        3
release_date    1
release_year    1
revenue         0
title           0
cast            0
crew            0
dtype: int64

In [14]:
data.dropna(inplace=True)

In [15]:
data.isnull().sum()

genres          0
id              0
keywords        0
overview        0
release_date    0
release_year    0
revenue         0
title           0
cast            0
crew            0
dtype: int64

In [16]:
data.shape

(4805, 10)

In [17]:
data.duplicated().sum()

np.int64(0)

In [18]:
import json

def genre_extract(col_value):
  l = []
  if isinstance(col_value, str):
    try:
      items = json.loads(col_value)
    except json.JSONDecodeError:
      return []
  elif isinstance(col_value, list):
    items = col_value
  else:
    return []

  for i in items:
    if isinstance(i, dict) and 'name' in i:
      l.append(i['name'])
    elif isinstance(i, str):
      l.append(i)
  return l

In [19]:

data['genres'] = data['genres'].apply(genre_extract)

In [20]:
import json

def keywords_extract(col_value):
  s = []
  if isinstance(col_value, str):
    try:
      items = json.loads(col_value)
    except json.JSONDecodeError:
      return []
  elif isinstance(col_value, list):
    items = col_value
  else:
    return []

  for item in items:
    if isinstance(item, dict) and 'name' in item:
      s.append(item['name'])
    elif isinstance(item, str):
      s.append(item)
  return s

In [21]:
data['keywords']=data['keywords'].apply(keywords_extract)

In [22]:
import json

def cast_extract(col_value):
  l = []
  if isinstance(col_value, str):
    try:
      items = json.loads(col_value)
    except json.JSONDecodeError:
      return []
  elif isinstance(col_value, list):
    items = col_value
  else:
    return []

  for item in items:
    if len(l) < 3:
      if isinstance(item, dict) and 'name' in item:
        l.append(item['name'])
      elif isinstance(item, str):
        l.append(item)
    else:
      break
  return l

data['cast'] = data['cast'].apply(cast_extract)

In [23]:
data['release_date']=pd.to_datetime(data['release_date'])

In [24]:
data['release_date'].dt.year

0       2009
1       2007
2       2015
3       2012
4       2012
        ...
4804    1992
4805    2011
4806    2013
4807    2012
4808    2005
Name: release_date, Length: 4805, dtype: int32

In [25]:
data.head(3)

,genres,id,keywords,overview,release_date,release_year,revenue,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",2009-12-10,2009.0,2787965087,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",2007-05-19,2007.0,961000000,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,2015-10-26,2015.0,880674609,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [26]:
import json

def crew_extract(col_value):
  l = []
  if isinstance(col_value, str):
    try:
      items = json.loads(col_value)
    except json.JSONDecodeError:
      return []
  elif isinstance(col_value, list):
    items = col_value
  else:
    return []

  for item in items:
    if isinstance(item, dict) and item.get('job') == 'Director':
      l.append(item.get('name'))
  return l

In [27]:
data['crew']=data['crew'].apply(crew_extract)

In [28]:
data.head()

,genres,id,keywords,overview,release_date,release_year,revenue,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",2009-12-10,2009.0,2787965087,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",2007-05-19,2007.0,961000000,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,2015-10-26,2015.0,880674609,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,2012-07-16,2012.0,1084939099,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",2012-03-07,2012.0,284139100,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
data['overview']=data['overview'].apply(lambda x:x.split())

In [30]:
data['cast'].apply(lambda x:[i.replace(" ","") for i in x])
data['crew'].apply(lambda x:[i.replace(" ","") for i in x])
data['genres'].apply(lambda x:[i.replace(" ","") for i in x])
data['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

0       [cultureclash, future, spacewar, spacecolony, ...
1       [ocean, drugabuse, exoticisland, eastindiatrad...
2       [spy, basedonnovel, secretagent, sequel, mi6, ...
3       [dccomics, crimefighter, terrorist, secretiden...
4       [basedonnovel, mars, medallion, spacetravel, p...
                              ...
4804    [unitedstates–mexicobarrier, legs, arms, paper...
4805                                                   []
4806    [date, loveatfirstsight, narration, investigat...
4807                                                   []
4808             [obsession, camcorder, crush, dreamgirl]
Name: keywords, Length: 4805, dtype: object

In [31]:
data.head(3)

,genres,id,keywords,overview,release_date,release_year,revenue,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",2009-12-10,2009.0,2787965087,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",2007-05-19,2007.0,961000000,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...",2015-10-26,2015.0,880674609,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [32]:
data['tags']=data['genres']+data['keywords']+data['cast']+data['crew']+data['overview']

In [33]:
data.drop(columns=['genres','keywords','cast','crew','release_year'],inplace=True)

In [34]:
data.head(3)

,id,overview,release_date,revenue,title,tags
0,19995,"[In, the, 22nd, century,, a, paraplegic, Marin...",2009-12-10,2787965087,Avatar,"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,"[Captain, Barbossa,, long, believed, to, be, d...",2007-05-19,961000000,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drug abuse..."
2,206647,"[A, cryptic, message, from, Bond’s, past, send...",2015-10-26,880674609,Spectre,"[Action, Adventure, Crime, spy, based on novel..."

In [35]:
data.drop(columns=['release_date','overview','revenue','release_date'],inplace=True)

In [36]:
data.head(3)

,id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drug abuse..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, based on novel..."

In [37]:
data['tags']=data['tags'].apply(lambda x:" ".join(x))

In [38]:
data.head(3)

,id,title,tags
0,19995,Avatar,Action Adventure Fantasy Science Fiction cultu...
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...
2,206647,Spectre,Action Adventure Crime spy based on novel secr...

In [39]:
data['tags'] = data['tags'].apply(lambda x: ' '.join(x).lower() if isinstance(x, list) else str(x).lower())

In [40]:
data.head(3)

,id,title,tags
0,19995,Avatar,action adventure fantasy science fiction cultu...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drug abuse exot...
2,206647,Spectre,action adventure crime spy based on novel secr...

In [41]:
from nltk.stem.porter  import PorterStemmer
ps=PorterStemmer()

In [42]:
data['tags'][0]

'action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d sam worthington zoe saldana sigourney weaver james cameron in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [43]:
def stemming(text):
  l=[]
  for i in text.split():
    l.append(ps.stem(i))
  return " ".join(l)

In [44]:
data['tags']=data['tags'].apply(stemming)

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(data['tags']).toarray()

In [46]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [47]:
cv.get_feature_names_out()[:200]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '16th', '17', '17th', '18', '18th', '19', '1910', '1920', '1930',
       '1940', '1950', '1950s', '1960', '1960s', '1970', '1970s', '1980',
       '1985', '1990', '19th', '20', '200', '2000', '2003', '2009',
       '20th', '21st', '23', '24', '25', '30', '300', '3d', '40', '50',
       '500', '51', '60', '70', 'aaron', 'abandon', 'abbi', 'abduct',
       'abigail', 'abil', 'abl', 'aboard', 'aborigin', 'abov', 'abraham',
       'abroad', 'abus', 'academ', 'academi', 'accent', 'accept',
       'access', 'accid', 'accident', 'acclaim', 'accompani',
       'accomplish', 'account', 'accus', 'ace', 'achiev', 'act', 'action',
       'activ', 'activist', 'activities', 'actor', 'actress', 'actual',
       'ad', 'adam', 'adapt', 'add', 'addict', 'adjust', 'admir', 'admit',
       'adolesc', 'adolf', 'adopt', 'ador', 'adrian', 'adrien', 'adult',
       'adulteri', 'adulthood', 'advanc', 'adventur', 'adventure',
       'advertis', 'advic', 'advis', 'affair', 'affect', 'affleck',
       'afghanistan', 'africa', 'african', 'aftercreditssting',
       'afterlif', 'aftermath', 'ag', 'age', 'agenc', 'agency', 'agenda',
       'agent', 'agents', 'aggress', 'ago', 'agre', 'ahead', 'aid',
       'aidan', 'ail', 'aim', 'air', 'aircraft', 'airplan', 'airport',
       'aka', 'al', 'alabama', 'alan', 'alaska', 'alba', 'albert',
       'alcatraz', 'alcohol', 'alec', 'alejandro', 'alex', 'alexand',
       'alexi', 'alfr', 'ali', 'alic', 'alice', 'alicia', 'alien', 'alik',
       'alison', 'aliv', 'alive', 'allan', 'allen', 'alli', 'allianc',
       'allison', 'allow', 'alon', 'alongsid', 'alpha', 'alreadi',
       'alter', 'altern', 'alway', 'alyssa', 'alzheimer', 'amanda',
       'amateur', 'amaz', 'amazon', 'ambassador', 'amber', 'ambigu',
       'ambit', 'ambiti', 'ambul', 'ambush', 'america', 'american', 'ami',
       'amid', 'amidst', 'amnesia', 'amp', 'amsterdam', 'amus', 'amy',
       'ana', 'analyst', 'anarch', 'ancient', 'anderson'], dtype=object)

In [48]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [49]:
similarity

array([[1.        , 0.06622662, 0.06554735, ..., 0.04442617, 0.03244428,
        0.        ],
       [0.06622662, 1.        , 0.0412393 , ..., 0.0372678 , 0.        ,
        0.01712972],
       [0.06554735, 0.0412393 , 1.        , ..., 0.01844278, 0.0808122 ,
        0.        ],
       ...,
       [0.04442617, 0.0372678 , 0.01844278, ..., 1.        , 0.03651484,
        0.03064257],
       [0.03244428, 0.        , 0.0808122 , ..., 0.03651484, 1.        ,
        0.06713451],
       [0.        , 0.01712972, 0.        , ..., 0.03064257, 0.06713451,
        1.        ]])

In [50]:
data[data['title']=='Avatar'].index[0]

np.int64(0)

In [51]:
def recommend(movie):
  movie_index=data[data['title']==movie].index[0]
  recomendations=similarity[movie_index]
  movie_list=sorted(enumerate(recomendations), reverse=True, key=lambda x:x[1])[1:6]
  for i in movie_list:
    print(data.iloc[i[0]].title)
  return recomendations

In [52]:
recommend('Avatar')

Aliens
Silent Running
Moonraker
Alien
Mission to Mars

array([1.        , 0.06622662, 0.06554735, ..., 0.04442617, 0.03244428,
       0.        ])

In [53]:
movie_list=sorted(enumerate(recommend('Avatar')), reverse=True, key=lambda x:x[1])[1:6]

Aliens
Silent Running
Moonraker
Alien
Mission to Mars

In [54]:
for i in movie_list:
  print(data.iloc[i[0]].title)

Aliens
Silent Running
Moonraker
Alien
Mission to Mars

In [55]:
recommend('Avatar')

Aliens
Silent Running
Moonraker
Alien
Mission to Mars

array([1.        , 0.06622662, 0.06554735, ..., 0.04442617, 0.03244428,
       0.        ])

In [57]:
import pickle
with open("movies.pickle",'wb') as movies:
  pickle.dump(data,movies)

In [60]:
from google.colab import files
files.download('movies.pickle')